name: OneTrust API Test

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      ONETRUST_CLIENT_ID: ${{ secrets.ONETRUST_CLIENT_ID }}
      ONETRUST_CLIENT_SECRET: ${{ secrets.ONETRUST_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python package
        run: python -m pip install requests

      - name: Run script
        run: python getinform.py
``
